name: Build README

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1" # Mondays 09:00 UTC

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest
    env:
      MAIN_USERNAME:        ${{ vars.MAIN_USERNAME }}
      ALT_USERNAME:         ${{ vars.ALT_USERNAME }}
      PUBLIC_EMAIL:         ${{ vars.PUBLIC_EMAIL }}
      X_HANDLE:             ${{ vars.X_HANDLE }}
      DISCORD_ID:           ${{ vars.DISCORD_ID }}
      COLLABO_ORG_USERNAME: ${{ vars.COLLABO_ORG_USERNAME }}
      COURIER_X_ORG_USERNAME: ${{ vars.COURIER_X_ORG_USERNAME }}

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set defaults and render README
        run: |
          # apply safe defaults if any var is missing
          : "${MAIN_USERNAME:=enochthedev}"
          : "${ALT_USERNAME:=wavedidwhat}"
          : "${PUBLIC_EMAIL:=wavedidwhat@gmail.com}"
          : "${X_HANDLE:=wavedidwhat}"
          : "${DISCORD_ID:=000000000000000000}"
          : "${COLLABO_ORG_USERNAME:=${MAIN_USERNAME}}"
          : "${COURIER_X_ORG_USERNAME:=${MAIN_USERNAME}}"

          export MAIN_USERNAME ALT_USERNAME PUBLIC_EMAIL X_HANDLE DISCORD_ID COLLABO_ORG_USERNAME COURIER_X_ORG_USERNAME

          # render README.md from template
          envsubst < README.template.md > README.md

      - name: Commit changes if any
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(readme): auto-render from template"
          file_pattern: README.md